#!/bin/bash

VERSION=`cat VERSION`

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg BUILD_VERSION=$VERSION \
             -t $IMAGE_NAME:latest \
             -t $IMAGE_NAME:$VERSION \
             .
